import { describe, expect, it } from "vitest";
import {
  findRuntimeFontFace,
  filterBunnyFontFaces,
  parseBunnyFontFaces,
  parseRuntimeFontFaces,
  parseRuntimeFontVariables,
  resolveContentFontRuntimeSlug,
  toFontFamilyLabel,
} from "../../server/utils/content-fonts";

const SAMPLE_CSS = `/* latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  font-stretch: 100%;
  src: url(https://fonts.bunny.net/inter/files/inter-latin-400-normal.woff2) format('woff2'), url(https://fonts.bunny.net/inter/files/inter-latin-400-normal.woff) format('woff');
  unicode-range: U+0000-00FF;
}

/* latin-ext */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  font-stretch: 75%;
  src: url(https://fonts.bunny.net/inter/files/inter-latin-ext-400-normal.woff2) format('woff2');
  unicode-range: U+0100-024F;
}

/* latin */
@font-face {
  font-family: 'Inter';
  font-style: italic;
  font-weight: 700;
  font-stretch: 100%;
  src: url(https://fonts.bunny.net/inter/files/inter-latin-700-italic.woff2) format('woff2');
  unicode-range: U+0000-00FF;
}`;

const RUNTIME_SAMPLE_CSS = `/* Generated by content font manager */
/* Montserrat */
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  font-stretch: 100%;
  font-display: swap;
  src: url('/fonts/managed/montserrat/montserrat-latin-400-normal-hash.woff2') format('woff2');
}
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  font-stretch: 125%;
  font-display: swap;
  src: url('/fonts/managed/montserrat/montserrat-latin-400-normal-wide-hash.woff2') format('woff2');
}
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 700;
  font-stretch: 100%;
  font-display: swap;
  src: url('/fonts/managed/montserrat/montserrat-latin-700-normal-hash.woff2') format('woff2');
}
:root {
  --font-sans: 'Montserrat', sans-serif;
  --font-display: 'Montserrat', serif;
}`;

const RUNTIME_ATTACHMENT_SAMPLE_CSS = `/* Generated by content font manager */
/* Montserrat */
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 700;
  font-stretch: 100%;
  font-display: fallback;
  src: url('/api/content/fonts/asset/montserrat-700-normal-100p-a1b2c3d4e5f6.woff2') format('woff2');
}
:root {
  --font-sans: 'Montserrat', sans-serif;
  --font-display: 'Montserrat', serif;
}`;

describe("content-fonts bunny css parsing", () => {
  it("extracts faces with metadata and woff2 source", () => {
    const faces = parseBunnyFontFaces(SAMPLE_CSS);

    expect(faces).toHaveLength(3);
    expect(faces[0]?.subset).toBe("latin");
    expect(faces[0]?.family).toBe("Inter");
    expect(faces[0]?.style).toBe("normal");
    expect(faces[0]?.weight).toBe(400);
    expect(faces[0]?.stretch).toBe("100%");
    expect(faces[0]?.remoteUrl).toContain("inter-latin-400-normal.woff2");
  });

  it("extracts runtime font faces with local managed asset paths", () => {
    const faces = parseRuntimeFontFaces(RUNTIME_SAMPLE_CSS);

    expect(faces).toHaveLength(3);
    expect(faces[0]).toMatchObject({
      family: "Montserrat",
      style: "normal",
      weight: 400,
      stretch: "100%",
    });
    expect(faces[0]?.publicUrl).toContain("/fonts/managed/montserrat/");
  });

  it("extracts runtime font faces with attachment-backed api asset paths", () => {
    const faces = parseRuntimeFontFaces(RUNTIME_ATTACHMENT_SAMPLE_CSS);

    expect(faces).toHaveLength(1);
    expect(faces[0]).toMatchObject({
      family: "Montserrat",
      style: "normal",
      weight: 700,
      stretch: "100%",
    });
    expect(faces[0]?.publicUrl).toContain("/api/content/fonts/asset/");
  });

  it("prefers exact stretch and falls back to 100% when selecting runtime face", () => {
    const faces = parseRuntimeFontFaces(RUNTIME_SAMPLE_CSS);

    const exact = findRuntimeFontFace(faces, {
      family: "Montserrat",
      style: "normal",
      weight: 400,
      stretch: "125%",
    });
    const fallback = findRuntimeFontFace(faces, {
      family: "Montserrat",
      style: "normal",
      weight: 400,
      stretch: "150%",
    });

    expect(exact?.publicUrl).toContain("wide-hash");
    expect(fallback?.publicUrl).toContain("normal-hash");
  });

  it("extracts runtime sans/display labels and slugs from css variables", () => {
    const parsed = parseRuntimeFontVariables(RUNTIME_SAMPLE_CSS);

    expect(parsed).toEqual({
      sansLabel: "Montserrat",
      displayLabel: "Montserrat",
      sansSlug: "montserrat",
      displaySlug: "montserrat",
    });
  });

  it("keeps latin subset only when available for requested styles/weights/widths", () => {
    const faces = parseBunnyFontFaces(SAMPLE_CSS);
    const filtered = filterBunnyFontFaces(faces, {
      styles: ["normal", "italic"],
      weights: [400, 700],
      widths: ["100%"],
    });

    expect(filtered).toHaveLength(2);
    expect(filtered.every((entry) => entry.subset === "latin")).toBe(true);
    expect(
      filtered.map((entry) => `${entry.style}-${entry.weight}-${entry.stretch}`),
    ).toEqual([
      "normal-400-100%",
      "italic-700-100%",
    ]);
  });

  it("converts slug to readable family label", () => {
    expect(toFontFamilyLabel("playfair-display")).toBe("Playfair Display");
  });

  it("prefers runtimeConfig.public.appSlug over process cwd for couch config slug resolution", () => {
    expect(
      resolveContentFontRuntimeSlug(
        {
          public: {
            appSlug: "bitvocation",
          },
        },
        "server",
      ),
    ).toBe("bitvocation");

    expect(resolveContentFontRuntimeSlug({}, "server")).toBe("server");
  });

});
